const { Telegraf } = require("telegraf");

const { botToken } = require("./config");
const { connectDB, closeDB } = require("./db");

const {
  routeAI
} = require("./ai/router");

const startHandler =
  require("./handlers/start");

const menuHandler =
  require("./handlers/menu");

const callbackHandler =
  require("./handlers/callbacks");

const {
  handleAccountText
} = require("./handlers/account");

const {
  checkMembership,
  showForceJoin
} = require("./middleware/forceJoin");

const {
  findByTelegramId,
  touchUser,
  getMemory
} = require("./services/userService");

const {
  saveChat,
  getRecentChats
} = require("./services/chatService");

const {
  startReminderWorker
} = require("./reminders");

const {
  isOwner
} = require("./utils/owner");

const {
  mainMenuKeyboard
} = require("./keyboards/menu");

const bot = new Telegraf(botToken);

const userQueues = new Map();
const SAFE_LIMIT = 3900;

function cleanAIResponse(text) {
  if (typeof text !== "string") {
    return String(text);
  }

  return text
    .replace(/```[\s\S]*?```/g, match =>
      match
        .replace(/```[a-zA-Z0-9_-]*\n?/g, "")
        .replace(/```/g, "")
    )
    .replace(/\*\*\*/g, "")
    .replace(/\*\*/g, "")
    .replace(/(?<!\w)\*(?!\w)/g, "")
    .replace(/^#{1,6}\s*/gm, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/^>\s?/gm, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .trim();
}

function splitMessage(text, limit = SAFE_LIMIT) {
  if (text.length <= limit) return [text];

  const chunks = [];
  let remaining = text;

  while (remaining.length > limit) {
    let cut = remaining.lastIndexOf("\n", limit);

    if (cut < limit * 0.5) {
      cut = remaining.lastIndexOf(" ", limit);
    }

    if (cut <= 0) cut = limit;

    chunks.push(
      remaining.slice(0, cut).trim()
    );

    remaining =
      remaining.slice(cut).trim();
  }

  if (remaining.length) {
    chunks.push(remaining);
  }

  return chunks;
}

function sleep(ms) {
  return new Promise(resolve =>
    setTimeout(resolve, ms)
  );
}

function isRetryableTelegramError(error) {
  const code = error?.code;
  const status =
    error?.response?.error_code;

  return [
    "ECONNABORTED",
    "ECONNRESET",
    "ETIMEDOUT",
    "EPIPE"
  ].includes(code) ||
    [
      408,
      425,
      429,
      500,
      502,
      503,
      504
    ].includes(status);
}

async function sendTelegramWithRetry(sendFunction) {
  const maxRetries = 3;

  for (
    let attempt = 0;
    attempt <= maxRetries;
    attempt++
  ) {
    try {
      return await sendFunction();
    } catch (error) {
      if (
        !isRetryableTelegramError(error) ||
        attempt === maxRetries
      ) {
        throw error;
      }

      await sleep(
        1500 * Math.pow(2, attempt)
      );
    }
  }
}

async function keepTyping(ctx, stopSignal) {
  while (!stopSignal.stopped) {
    try {
      await ctx.sendChatAction("typing");
    } catch {}

    await sleep(4000);
  }
}

async function processMessage(ctx, user, message) {
  const stopSignal = {
    stopped: false
  };

  const typingPromise =
    keepTyping(ctx, stopSignal);

  try {
    const memory =
      await getMemory(user._id);

    const history =
      await getRecentChats(
        user._id,
        12
      );

    const response =
      await routeAI({
        message,
        memory,
        reasoningLevel:
          user.settings?.reasoningLevel ||
          "standard",
        history
      });

    stopSignal.stopped = true;

    await typingPromise;

    await saveChat({
      userId: user._id,
      telegramId: ctx.from.id,
      role: "user",
      text: message,
      engine: response.engine
    });

    if (response.type === "image") {
      await sendTelegramWithRetry(() =>
        ctx.replyWithPhoto(
          {
            source: response.result
          },
          {
            caption:
              "🎨 Generated by Entity 4.5"
          }
        )
      );

      await saveChat({
        userId: user._id,
        telegramId: ctx.from.id,
        role: "assistant",
        text: "[Image generated]",
        engine: response.engine
      });

      return;
    }

    const cleaned =
      cleanAIResponse(
        response.result
      );

    const chunks =
      splitMessage(cleaned);

    for (const chunk of chunks) {
      await sendTelegramWithRetry(() =>
        ctx.reply(chunk)
      );
    }

    await saveChat({
      userId: user._id,
      telegramId: ctx.from.id,
      role: "assistant",
      text: cleaned,
      engine: response.engine
    });
  } catch (error) {
    stopSignal.stopped = true;

    try {
      await typingPromise;
    } catch {}

    console.error(
      "AI error:",
      error
    );

    await ctx.reply(
      `⚠️ Entity 4.5 encountered an error while processing your request.\n\nPlease try again.`
    );
  }
}

function queueMessage(userId, task) {
  const previous =
    userQueues.get(userId) ||
    Promise.resolve();

  const next = previous
    .catch(() => {})
    .then(task);

  userQueues.set(
    userId,
    next.finally(() => {
      if (
        userQueues.get(userId) === next
      ) {
        userQueues.delete(userId);
      }
    })
  );

  return next;
}

bot.start(async ctx => {
  try {
    await startHandler(ctx);
  } catch (error) {
    console.error(
      "Start handler error:",
      error
    );

    await ctx.reply(
      "⚠️ Something went wrong. Please try /start again."
    );
  }
});

bot.help(async ctx => {
  const joined =
    await checkMembership(ctx);

  if (!joined) {
    await showForceJoin(ctx);
    return;
  }

  await ctx.reply(
    `🐕 ENTITY 4.5

The dog without limits.

You can:
• Chat with Entity 4.5
• Ask research-style questions
• Generate code
• Generate images
• Keep account-based memory

Use /menu to open the control panel.`
  );
});

bot.command("menu", async ctx => {
  const joined =
    await checkMembership(ctx);

  if (!joined) {
    await showForceJoin(ctx);
    return;
  }

  await menuHandler(ctx);
});

bot.command("cancel", async ctx => {
  const {
    clearSession
  } = require("./services/sessionService");

  clearSession(ctx.from.id);

  await ctx.reply(
    "❌ Current operation cancelled."
  );
});

bot.on("callback_query", async ctx => {
  try {
    await callbackHandler(ctx);
  } catch (error) {
    console.error(
      "Callback error:",
      error
    );

    try {
      await ctx.answerCbQuery(
        "Something went wrong."
      );
    } catch {}
  }
});

bot.on("text", async ctx => {
  const message =
    ctx.message.text?.trim();

  if (!message) return;

  const joined =
    await checkMembership(ctx);

  if (!joined) {
    await showForceJoin(ctx);
    return;
  }

  const accountHandled =
    await handleAccountText(
      ctx,
      message
    );

  if (accountHandled) {
    return;
  }

  const user =
    await findByTelegramId(
      ctx.from.id
    );

  if (!user) {
    await ctx.reply(
      `🔐 ACCOUNT REQUIRED

Create an Entity account or login before chatting.

Use /menu.`,
      mainMenuKeyboard({
        owner: isOwner(ctx.from.id)
      })
    );

    return;
  }

  await touchUser(user._id);

  await queueMessage(
    user._id.toString(),
    () =>
      processMessage(
        ctx,
        user,
        message
      )
  );
});

bot.catch(async (error, ctx) => {
  console.error(
    "Global bot error:",
    error
  );

  try {
    await ctx.reply(
      "⚠️ An unexpected error occurred. Please try again."
    );
  } catch {}
});

async function startBot() {
  await connectDB();

  await bot.launch();

  startReminderWorker(bot);

  console.log(
    "🐕 Entity 4.5 Phase 3 is online."
  );
}

startBot().catch(error => {
  console.error(
    "Failed to start:",
    error
  );

  process.exit(1);
});

async function shutdown(signal) {
  try {
    bot.stop(signal);
    await closeDB();
  } finally {
    process.exit(0);
  }
}

process.once(
  "SIGINT",
  () => shutdown("SIGINT")
);

process.once(
  "SIGTERM",
  () => shutdown("SIGTERM")
);
